### ISSUE TITLE
Recognize text with hyphen

### ISSUE THREAD

**Issue by george-i** [winkjs/wink-ner#27]
```
var ner = require( 'wink-ner' );
var myNER = ner();
myNER .defineConfig({ignoreDiacritics: true, tagsToIgnore: ['punctuation'], valuesToIgnore: []});

var trainingData = [
  { text: 'T-Mobile', entityType: 'company', symbol: 'TMUS' }
];

myNER.learn( trainingData );
var winkTokenizer = require( 'wink-tokenizer' );
var tokenize = winkTokenizer().tokenize;
var tokens = tokenize( 'I work for T-Mobile and I like it' );
tokens = myNER.recognize( tokens );
console.log( tokens );

```

'**T-Mobile**' is not recognized although punctuation is specified in `defineConfig`.

**Comment by sanjayaksaxena** [comment]
Here is the revised code:

```javascript
var ner = require( 'wink-ner' );
var myNER = ner();

var trainingData = [
  { text: 'T Mobile', entityType: 'company', symbol: 'TMUS' }
];

myNER.learn( trainingData );
var winkTokenizer = require( 'wink-tokenizer' );
var tokenize = winkTokenizer().tokenize;
var tokens = tokenize( 'I work for T-Mobile and I like it' );
tokens = myNER.recognize( tokens );
console.log( tokens );
```

#### Output:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/29990/135320235-23df7617-a5c0-45e3-bee7-1a6a8e5ddcb0.png">

Since we are ignoring punctuation, we need to exclude the same in the training data. This is mentioned in the [learn()](https://winkjs.org/wink-ner/NER.html#learn) API — the text needs to be improved and details have to be clearly mentioned — will update the document soon.

Thanks for highlighting the issue. You may like to explore [wink-nlp](https://github.com/winkjs/wink-nlp) for more advance use cases — this is an integrated NLP tool.
